#if !canImport(ObjectiveC)
import XCTest

extension TelegramLogHandlerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TelegramLogHandlerTests = [
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(TelegramLogHandlerTests.__allTests__TelegramLogHandlerTests)
    ]
}
#endif
